use app;
SELECT 
    *
FROM
    playstore_apps_clean_final;

# 1. Which apps have the highest rating in the given available dataset?
SELECT 
    app, category, rating
FROM
    playstore_apps_clean_final
WHERE
    rating = (SELECT 
            MAX(rating)
        FROM
            playstore_apps_clean_final);

# 2.What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top.
SELECT 
    app, category, rating, installs, reviews
FROM
    playstore_apps_clean_final
WHERE
    rating = (SELECT 
            MAX(rating)
        FROM
            playstore_apps_clean_final)
ORDER BY reviews DESC;

# 3.Which app has the highest number of reviews? Also, mention the number of reviews and category of the app.
SELECT 
    app, category, reviews
FROM
    playstore_apps_clean_final
ORDER BY reviews DESC
LIMIT 1;

# 4.What is the total amount of revenue generated by the google play store by hosting apps?
SELECT 
    SUM(price)
FROM
    playstore_apps_clean_final;

# 5.Which Category of google play store apps has the highest number of installs?
# also, find out the total number of installs for that particular category.
SELECT DISTINCT
    (category), app, installs
FROM
    playstore_apps_clean_final
ORDER BY installs DESC
LIMIT 1;

# 6.Which Genre has the most number of published apps?
SELECT 
    genres, COUNT(genres)
FROM
    playstore_apps_clean_final
GROUP BY genres
ORDER BY COUNT(genres) DESC
LIMIT 1;

SELECT 
    genres, COUNT(genres)
FROM
    playstore_apps_clean_final
WHERE
    genres = 'tools';
    
# 7.Provide the list of all games ordered in such a way that the game that has the highest number of installs is displayed on the top
SELECT DISTINCT
    (app), category, installs
FROM
    playstore_apps_clean_final
WHERE
    category = 'game'
ORDER BY category , installs DESC;

#8.Provide the list of apps that can work on android version 4.0.3 and UP.
SELECT DISTINCT
    (app), androidver
FROM
    playstore_apps_clean_final
WHERE
    androidver = '4.0.3 and up';

# 9.How many apps from the given data set are free? Also, provide the number of paid apps.
SELECT 
    type, COUNT(type)
FROM
    playstore_apps_clean_final
WHERE
    type = 'free';
SELECT 
    type, COUNT(type)
FROM
    playstore_apps_clean_final
WHERE
    type = 'paid';

# 10.Which is the best dating app?
SELECT 
    *
FROM
    playstore_apps_clean_final;
SELECT 
    app, category, MAX(reviews)
FROM
    playstore_apps_clean_final
WHERE
    category = 'dating';

# 11.Get the number of reviews having positive sentiment and number of reviews having negative sentiment 
# for the app 10 best foods for you and compare them.
SELECT 
    *
FROM
    playstore_reviews_final;
SELECT 
    COUNT(*)
FROM
    playstore_reviews_final;
SELECT 
    app, sentiment, COUNT(sentiment)
FROM
    playstore_reviews_final
WHERE
    sentiment = 'negative'
        AND app = '10 Best Foods for You';
SELECT 
    app, sentiment, COUNT(sentiment)
FROM
    playstore_reviews_final
WHERE
    sentiment = 'positive'
        AND app = '10 Best Foods for You';

# 12. Which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1?
SELECT 
    app,
    translatedreview,
    sentimentpolarity,
    sentimentsubjectivity
FROM
    playstore_reviews_final
WHERE
    app = 'asus supernote'
        AND sentimentpolarity = 1
        AND sentimentsubjectivity = 1;

# 13.Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat 
SELECT 
    *
FROM
    playstore_reviews_final;
SELECT 
    app, translatedreview, sentiment
FROM
    playstore_reviews_final
WHERE
    app = 'Abs Training-Burn belly fat'
        AND sentiment = 'neutral';

# 14.Extract all negative sentiment reviews for Adobe Acrobat Reader with their sentiment polarity 
#and sentiment subjectivity

SELECT 
    *
FROM
    playstore_reviews_final
WHERE
    app = 'Adobe Acrobat Reader'
        AND sentiment = 'negative';